/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * API version: 2020-09-14_1.652.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plaid

import (
	"encoding/json"
)

// CashFlowUpdatesInsightsWebhook For each user's item enabled for Cash Flow Updates, this webhook will fire between one and four times a day with information on the status of the update. Upon receiving the webhook, call `/cra/monitoring_insights/get` to retrieve the updated insights.
type CashFlowUpdatesInsightsWebhook struct {
	// `CASH_FLOW_UPDATES`
	WebhookType string `json:"webhook_type"`
	// `INSIGHTS_UPDATED`
	WebhookCode string `json:"webhook_code"`
	Status MonitoringInsightsStatus `json:"status"`
	// The `user_id` that the report is associated with
	UserId string `json:"user_id"`
	Environment WebhookEnvironmentValues `json:"environment"`
	AdditionalProperties map[string]interface{}
}

type _CashFlowUpdatesInsightsWebhook CashFlowUpdatesInsightsWebhook

// NewCashFlowUpdatesInsightsWebhook instantiates a new CashFlowUpdatesInsightsWebhook object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCashFlowUpdatesInsightsWebhook(webhookType string, webhookCode string, status MonitoringInsightsStatus, userId string, environment WebhookEnvironmentValues) *CashFlowUpdatesInsightsWebhook {
	this := CashFlowUpdatesInsightsWebhook{}
	this.WebhookType = webhookType
	this.WebhookCode = webhookCode
	this.Status = status
	this.UserId = userId
	this.Environment = environment
	return &this
}

// NewCashFlowUpdatesInsightsWebhookWithDefaults instantiates a new CashFlowUpdatesInsightsWebhook object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCashFlowUpdatesInsightsWebhookWithDefaults() *CashFlowUpdatesInsightsWebhook {
	this := CashFlowUpdatesInsightsWebhook{}
	return &this
}

// GetWebhookType returns the WebhookType field value
func (o *CashFlowUpdatesInsightsWebhook) GetWebhookType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WebhookType
}

// GetWebhookTypeOk returns a tuple with the WebhookType field value
// and a boolean to check if the value has been set.
func (o *CashFlowUpdatesInsightsWebhook) GetWebhookTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.WebhookType, true
}

// SetWebhookType sets field value
func (o *CashFlowUpdatesInsightsWebhook) SetWebhookType(v string) {
	o.WebhookType = v
}

// GetWebhookCode returns the WebhookCode field value
func (o *CashFlowUpdatesInsightsWebhook) GetWebhookCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WebhookCode
}

// GetWebhookCodeOk returns a tuple with the WebhookCode field value
// and a boolean to check if the value has been set.
func (o *CashFlowUpdatesInsightsWebhook) GetWebhookCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.WebhookCode, true
}

// SetWebhookCode sets field value
func (o *CashFlowUpdatesInsightsWebhook) SetWebhookCode(v string) {
	o.WebhookCode = v
}

// GetStatus returns the Status field value
func (o *CashFlowUpdatesInsightsWebhook) GetStatus() MonitoringInsightsStatus {
	if o == nil {
		var ret MonitoringInsightsStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CashFlowUpdatesInsightsWebhook) GetStatusOk() (*MonitoringInsightsStatus, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CashFlowUpdatesInsightsWebhook) SetStatus(v MonitoringInsightsStatus) {
	o.Status = v
}

// GetUserId returns the UserId field value
func (o *CashFlowUpdatesInsightsWebhook) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *CashFlowUpdatesInsightsWebhook) GetUserIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *CashFlowUpdatesInsightsWebhook) SetUserId(v string) {
	o.UserId = v
}

// GetEnvironment returns the Environment field value
func (o *CashFlowUpdatesInsightsWebhook) GetEnvironment() WebhookEnvironmentValues {
	if o == nil {
		var ret WebhookEnvironmentValues
		return ret
	}

	return o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value
// and a boolean to check if the value has been set.
func (o *CashFlowUpdatesInsightsWebhook) GetEnvironmentOk() (*WebhookEnvironmentValues, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Environment, true
}

// SetEnvironment sets field value
func (o *CashFlowUpdatesInsightsWebhook) SetEnvironment(v WebhookEnvironmentValues) {
	o.Environment = v
}

func (o CashFlowUpdatesInsightsWebhook) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["webhook_type"] = o.WebhookType
	}
	if true {
		toSerialize["webhook_code"] = o.WebhookCode
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if true {
		toSerialize["user_id"] = o.UserId
	}
	if true {
		toSerialize["environment"] = o.Environment
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *CashFlowUpdatesInsightsWebhook) UnmarshalJSON(bytes []byte) (err error) {
	varCashFlowUpdatesInsightsWebhook := _CashFlowUpdatesInsightsWebhook{}

	if err = json.Unmarshal(bytes, &varCashFlowUpdatesInsightsWebhook); err == nil {
		*o = CashFlowUpdatesInsightsWebhook(varCashFlowUpdatesInsightsWebhook)
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "webhook_type")
		delete(additionalProperties, "webhook_code")
		delete(additionalProperties, "status")
		delete(additionalProperties, "user_id")
		delete(additionalProperties, "environment")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCashFlowUpdatesInsightsWebhook struct {
	value *CashFlowUpdatesInsightsWebhook
	isSet bool
}

func (v NullableCashFlowUpdatesInsightsWebhook) Get() *CashFlowUpdatesInsightsWebhook {
	return v.value
}

func (v *NullableCashFlowUpdatesInsightsWebhook) Set(val *CashFlowUpdatesInsightsWebhook) {
	v.value = val
	v.isSet = true
}

func (v NullableCashFlowUpdatesInsightsWebhook) IsSet() bool {
	return v.isSet
}

func (v *NullableCashFlowUpdatesInsightsWebhook) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCashFlowUpdatesInsightsWebhook(val *CashFlowUpdatesInsightsWebhook) *NullableCashFlowUpdatesInsightsWebhook {
	return &NullableCashFlowUpdatesInsightsWebhook{value: val, isSet: true}
}

func (v NullableCashFlowUpdatesInsightsWebhook) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCashFlowUpdatesInsightsWebhook) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


