/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * API version: 2020-09-14_1.698.7
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plaid

import (
	"encoding/json"
	"fmt"
)

// RiskCheckEmailName Indicates whether the provided name matches the email address according to the KYC name-matches-email inference result if known.  `match` - \"The email's name identifiers match the user's name.\"  `partial_match` - \"The email's name identifiers partially match the user's name.\"  `no_match` - \"The email's name identifiers do not match the user's name.\"  `indeterminate` - \"The email does not contain any name identifiers, and a match could not be determined.\"  `no_input` - \"The user's profile does not contain the required user inputs to determine a match.\"  `no_data` - \"Field could not be verified against available sources.\"
type RiskCheckEmailName string

var _ = fmt.Printf

// List of RiskCheckEmailName
const (
	RISKCHECKEMAILNAME_NO_INPUT RiskCheckEmailName = "no_input"
	RISKCHECKEMAILNAME_INDETERMINATE RiskCheckEmailName = "indeterminate"
	RISKCHECKEMAILNAME_NO_MATCH RiskCheckEmailName = "no_match"
	RISKCHECKEMAILNAME_PARTIAL_MATCH RiskCheckEmailName = "partial_match"
	RISKCHECKEMAILNAME_MATCH RiskCheckEmailName = "match"
	RISKCHECKEMAILNAME_NO_DATA RiskCheckEmailName = "no_data"
)

var allowedRiskCheckEmailNameEnumValues = []RiskCheckEmailName{
	"no_input",
	"indeterminate",
	"no_match",
	"partial_match",
	"match",
	"no_data",
}

func (v *RiskCheckEmailName) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}

	enumTypeValue := RiskCheckEmailName(value)


	*v = enumTypeValue
	return nil
}

// NewRiskCheckEmailNameFromValue returns a pointer to a valid RiskCheckEmailName
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRiskCheckEmailNameFromValue(v string) (*RiskCheckEmailName, error) {
	ev := RiskCheckEmailName(v)


	return &ev, nil
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RiskCheckEmailName) IsValid() bool {
	for _, existing := range allowedRiskCheckEmailNameEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RiskCheckEmailName value
func (v RiskCheckEmailName) Ptr() *RiskCheckEmailName {
	return &v
}

type NullableRiskCheckEmailName struct {
	value *RiskCheckEmailName
	isSet bool
}

func (v NullableRiskCheckEmailName) Get() *RiskCheckEmailName {
	return v.value
}

func (v *NullableRiskCheckEmailName) Set(val *RiskCheckEmailName) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskCheckEmailName) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskCheckEmailName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskCheckEmailName(val *RiskCheckEmailName) *NullableRiskCheckEmailName {
	return &NullableRiskCheckEmailName{value: val, isSet: true}
}

func (v NullableRiskCheckEmailName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskCheckEmailName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

