/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * API version: 2020-09-14_1.21.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plaid

import (
	"encoding/json"
)

// BankTransferUser The legal name and other information for the account holder.
type BankTransferUser struct {
	// The user's legal name.
	LegalName string `json:"legal_name"`
	// The user's phone number.
	PhoneNumber *string `json:"phone_number,omitempty"`
	// The user's email address.
	EmailAddress *string `json:"email_address,omitempty"`
	// The account holder's routing number. This field is only used in response data. Do not provide this field when making requests.
	RoutingNumber *string `json:"routing_number,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BankTransferUser BankTransferUser

// NewBankTransferUser instantiates a new BankTransferUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBankTransferUser(legalName string) *BankTransferUser {
	this := BankTransferUser{}
	this.LegalName = legalName
	return &this
}

// NewBankTransferUserWithDefaults instantiates a new BankTransferUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBankTransferUserWithDefaults() *BankTransferUser {
	this := BankTransferUser{}
	return &this
}

// GetLegalName returns the LegalName field value
func (o *BankTransferUser) GetLegalName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LegalName
}

// GetLegalNameOk returns a tuple with the LegalName field value
// and a boolean to check if the value has been set.
func (o *BankTransferUser) GetLegalNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.LegalName, true
}

// SetLegalName sets field value
func (o *BankTransferUser) SetLegalName(v string) {
	o.LegalName = v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *BankTransferUser) GetPhoneNumber() string {
	if o == nil || o.PhoneNumber == nil {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankTransferUser) GetPhoneNumberOk() (*string, bool) {
	if o == nil || o.PhoneNumber == nil {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *BankTransferUser) HasPhoneNumber() bool {
	if o != nil && o.PhoneNumber != nil {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *BankTransferUser) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

// GetEmailAddress returns the EmailAddress field value if set, zero value otherwise.
func (o *BankTransferUser) GetEmailAddress() string {
	if o == nil || o.EmailAddress == nil {
		var ret string
		return ret
	}
	return *o.EmailAddress
}

// GetEmailAddressOk returns a tuple with the EmailAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankTransferUser) GetEmailAddressOk() (*string, bool) {
	if o == nil || o.EmailAddress == nil {
		return nil, false
	}
	return o.EmailAddress, true
}

// HasEmailAddress returns a boolean if a field has been set.
func (o *BankTransferUser) HasEmailAddress() bool {
	if o != nil && o.EmailAddress != nil {
		return true
	}

	return false
}

// SetEmailAddress gets a reference to the given string and assigns it to the EmailAddress field.
func (o *BankTransferUser) SetEmailAddress(v string) {
	o.EmailAddress = &v
}

// GetRoutingNumber returns the RoutingNumber field value if set, zero value otherwise.
func (o *BankTransferUser) GetRoutingNumber() string {
	if o == nil || o.RoutingNumber == nil {
		var ret string
		return ret
	}
	return *o.RoutingNumber
}

// GetRoutingNumberOk returns a tuple with the RoutingNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BankTransferUser) GetRoutingNumberOk() (*string, bool) {
	if o == nil || o.RoutingNumber == nil {
		return nil, false
	}
	return o.RoutingNumber, true
}

// HasRoutingNumber returns a boolean if a field has been set.
func (o *BankTransferUser) HasRoutingNumber() bool {
	if o != nil && o.RoutingNumber != nil {
		return true
	}

	return false
}

// SetRoutingNumber gets a reference to the given string and assigns it to the RoutingNumber field.
func (o *BankTransferUser) SetRoutingNumber(v string) {
	o.RoutingNumber = &v
}

func (o BankTransferUser) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["legal_name"] = o.LegalName
	}
	if o.PhoneNumber != nil {
		toSerialize["phone_number"] = o.PhoneNumber
	}
	if o.EmailAddress != nil {
		toSerialize["email_address"] = o.EmailAddress
	}
	if o.RoutingNumber != nil {
		toSerialize["routing_number"] = o.RoutingNumber
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *BankTransferUser) UnmarshalJSON(bytes []byte) (err error) {
	varBankTransferUser := _BankTransferUser{}

	if err = json.Unmarshal(bytes, &varBankTransferUser); err == nil {
		*o = BankTransferUser(varBankTransferUser)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "legal_name")
		delete(additionalProperties, "phone_number")
		delete(additionalProperties, "email_address")
		delete(additionalProperties, "routing_number")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBankTransferUser struct {
	value *BankTransferUser
	isSet bool
}

func (v NullableBankTransferUser) Get() *BankTransferUser {
	return v.value
}

func (v *NullableBankTransferUser) Set(val *BankTransferUser) {
	v.value = val
	v.isSet = true
}

func (v NullableBankTransferUser) IsSet() bool {
	return v.isSet
}

func (v *NullableBankTransferUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBankTransferUser(val *BankTransferUser) *NullableBankTransferUser {
	return &NullableBankTransferUser{value: val, isSet: true}
}

func (v NullableBankTransferUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBankTransferUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


