/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * API version: 2020-09-14_1.391.2
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plaid

import (
	"encoding/json"
)

// CreditFreddieMacPartyIndividualVOA24 Documentation not found in the MISMO model viewer and not provided by Freddie Mac.
type CreditFreddieMacPartyIndividualVOA24 struct {
	NAME CreditFreddieMacIndividualNameVOA24 `json:"NAME"`
	AdditionalProperties map[string]interface{}
}

type _CreditFreddieMacPartyIndividualVOA24 CreditFreddieMacPartyIndividualVOA24

// NewCreditFreddieMacPartyIndividualVOA24 instantiates a new CreditFreddieMacPartyIndividualVOA24 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreditFreddieMacPartyIndividualVOA24(nAME CreditFreddieMacIndividualNameVOA24) *CreditFreddieMacPartyIndividualVOA24 {
	this := CreditFreddieMacPartyIndividualVOA24{}
	this.NAME = nAME
	return &this
}

// NewCreditFreddieMacPartyIndividualVOA24WithDefaults instantiates a new CreditFreddieMacPartyIndividualVOA24 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreditFreddieMacPartyIndividualVOA24WithDefaults() *CreditFreddieMacPartyIndividualVOA24 {
	this := CreditFreddieMacPartyIndividualVOA24{}
	return &this
}

// GetNAME returns the NAME field value
func (o *CreditFreddieMacPartyIndividualVOA24) GetNAME() CreditFreddieMacIndividualNameVOA24 {
	if o == nil {
		var ret CreditFreddieMacIndividualNameVOA24
		return ret
	}

	return o.NAME
}

// GetNAMEOk returns a tuple with the NAME field value
// and a boolean to check if the value has been set.
func (o *CreditFreddieMacPartyIndividualVOA24) GetNAMEOk() (*CreditFreddieMacIndividualNameVOA24, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.NAME, true
}

// SetNAME sets field value
func (o *CreditFreddieMacPartyIndividualVOA24) SetNAME(v CreditFreddieMacIndividualNameVOA24) {
	o.NAME = v
}

func (o CreditFreddieMacPartyIndividualVOA24) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["NAME"] = o.NAME
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *CreditFreddieMacPartyIndividualVOA24) UnmarshalJSON(bytes []byte) (err error) {
	varCreditFreddieMacPartyIndividualVOA24 := _CreditFreddieMacPartyIndividualVOA24{}

	if err = json.Unmarshal(bytes, &varCreditFreddieMacPartyIndividualVOA24); err == nil {
		*o = CreditFreddieMacPartyIndividualVOA24(varCreditFreddieMacPartyIndividualVOA24)
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "NAME")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreditFreddieMacPartyIndividualVOA24 struct {
	value *CreditFreddieMacPartyIndividualVOA24
	isSet bool
}

func (v NullableCreditFreddieMacPartyIndividualVOA24) Get() *CreditFreddieMacPartyIndividualVOA24 {
	return v.value
}

func (v *NullableCreditFreddieMacPartyIndividualVOA24) Set(val *CreditFreddieMacPartyIndividualVOA24) {
	v.value = val
	v.isSet = true
}

func (v NullableCreditFreddieMacPartyIndividualVOA24) IsSet() bool {
	return v.isSet
}

func (v *NullableCreditFreddieMacPartyIndividualVOA24) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreditFreddieMacPartyIndividualVOA24(val *CreditFreddieMacPartyIndividualVOA24) *NullableCreditFreddieMacPartyIndividualVOA24 {
	return &NullableCreditFreddieMacPartyIndividualVOA24{value: val, isSet: true}
}

func (v NullableCreditFreddieMacPartyIndividualVOA24) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreditFreddieMacPartyIndividualVOA24) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


