/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * API version: 2020-09-14_1.681.4
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plaid

import (
	"encoding/json"
)

// ProtectUser Represents an end user for /protect/compute requests.
type ProtectUser struct {
	// The Plaid User ID returned from a previous call to `/user/create`. This or `client_user_id` can be provided, not both.
	UserId *string `json:"user_id,omitempty"`
	// A unique ID representing the end user. Maximum of 128 characters. Typically this will be a user ID number from your application. Personally identifiable information, such as an email address or phone number, should not be used in the `client_user_id`.
	ClientUserId *string `json:"client_user_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProtectUser ProtectUser

// NewProtectUser instantiates a new ProtectUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProtectUser() *ProtectUser {
	this := ProtectUser{}
	return &this
}

// NewProtectUserWithDefaults instantiates a new ProtectUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProtectUserWithDefaults() *ProtectUser {
	this := ProtectUser{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *ProtectUser) GetUserId() string {
	if o == nil || o.UserId == nil {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtectUser) GetUserIdOk() (*string, bool) {
	if o == nil || o.UserId == nil {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *ProtectUser) HasUserId() bool {
	if o != nil && o.UserId != nil {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *ProtectUser) SetUserId(v string) {
	o.UserId = &v
}

// GetClientUserId returns the ClientUserId field value if set, zero value otherwise.
func (o *ProtectUser) GetClientUserId() string {
	if o == nil || o.ClientUserId == nil {
		var ret string
		return ret
	}
	return *o.ClientUserId
}

// GetClientUserIdOk returns a tuple with the ClientUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtectUser) GetClientUserIdOk() (*string, bool) {
	if o == nil || o.ClientUserId == nil {
		return nil, false
	}
	return o.ClientUserId, true
}

// HasClientUserId returns a boolean if a field has been set.
func (o *ProtectUser) HasClientUserId() bool {
	if o != nil && o.ClientUserId != nil {
		return true
	}

	return false
}

// SetClientUserId gets a reference to the given string and assigns it to the ClientUserId field.
func (o *ProtectUser) SetClientUserId(v string) {
	o.ClientUserId = &v
}

func (o ProtectUser) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.UserId != nil {
		toSerialize["user_id"] = o.UserId
	}
	if o.ClientUserId != nil {
		toSerialize["client_user_id"] = o.ClientUserId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *ProtectUser) UnmarshalJSON(bytes []byte) (err error) {
	varProtectUser := _ProtectUser{}

	if err = json.Unmarshal(bytes, &varProtectUser); err == nil {
		*o = ProtectUser(varProtectUser)
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "user_id")
		delete(additionalProperties, "client_user_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProtectUser struct {
	value *ProtectUser
	isSet bool
}

func (v NullableProtectUser) Get() *ProtectUser {
	return v.value
}

func (v *NullableProtectUser) Set(val *ProtectUser) {
	v.value = val
	v.isSet = true
}

func (v NullableProtectUser) IsSet() bool {
	return v.isSet
}

func (v *NullableProtectUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProtectUser(val *ProtectUser) *NullableProtectUser {
	return &NullableProtectUser{value: val, isSet: true}
}

func (v NullableProtectUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProtectUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


