/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * API version: 2020-09-14_1.729.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plaid

import (
	"encoding/json"
	"fmt"
)

// BetaIssuesV1MatchIdentifierType The type of identifier supplied to `/beta/issues/v1/match`.
type BetaIssuesV1MatchIdentifierType string

var _ = fmt.Printf

// List of BetaIssuesV1MatchIdentifierType
const (
	BETAISSUESV1MATCHIDENTIFIERTYPE_ITEM_ID BetaIssuesV1MatchIdentifierType = "ITEM_ID"
	BETAISSUESV1MATCHIDENTIFIERTYPE_REQUEST_ID BetaIssuesV1MatchIdentifierType = "REQUEST_ID"
	BETAISSUESV1MATCHIDENTIFIERTYPE_LINK_SESSION_ID BetaIssuesV1MatchIdentifierType = "LINK_SESSION_ID"
	BETAISSUESV1MATCHIDENTIFIERTYPE_ACCOUNT_ID BetaIssuesV1MatchIdentifierType = "ACCOUNT_ID"
)

var allowedBetaIssuesV1MatchIdentifierTypeEnumValues = []BetaIssuesV1MatchIdentifierType{
	"ITEM_ID",
	"REQUEST_ID",
	"LINK_SESSION_ID",
	"ACCOUNT_ID",
}

func (v *BetaIssuesV1MatchIdentifierType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}

	enumTypeValue := BetaIssuesV1MatchIdentifierType(value)


	*v = enumTypeValue
	return nil
}

// NewBetaIssuesV1MatchIdentifierTypeFromValue returns a pointer to a valid BetaIssuesV1MatchIdentifierType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBetaIssuesV1MatchIdentifierTypeFromValue(v string) (*BetaIssuesV1MatchIdentifierType, error) {
	ev := BetaIssuesV1MatchIdentifierType(v)


	return &ev, nil
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BetaIssuesV1MatchIdentifierType) IsValid() bool {
	for _, existing := range allowedBetaIssuesV1MatchIdentifierTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BetaIssuesV1MatchIdentifierType value
func (v BetaIssuesV1MatchIdentifierType) Ptr() *BetaIssuesV1MatchIdentifierType {
	return &v
}

type NullableBetaIssuesV1MatchIdentifierType struct {
	value *BetaIssuesV1MatchIdentifierType
	isSet bool
}

func (v NullableBetaIssuesV1MatchIdentifierType) Get() *BetaIssuesV1MatchIdentifierType {
	return v.value
}

func (v *NullableBetaIssuesV1MatchIdentifierType) Set(val *BetaIssuesV1MatchIdentifierType) {
	v.value = val
	v.isSet = true
}

func (v NullableBetaIssuesV1MatchIdentifierType) IsSet() bool {
	return v.isSet
}

func (v *NullableBetaIssuesV1MatchIdentifierType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBetaIssuesV1MatchIdentifierType(val *BetaIssuesV1MatchIdentifierType) *NullableBetaIssuesV1MatchIdentifierType {
	return &NullableBetaIssuesV1MatchIdentifierType{value: val, isSet: true}
}

func (v NullableBetaIssuesV1MatchIdentifierType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBetaIssuesV1MatchIdentifierType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

