/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * API version: 2020-09-14_1.740.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plaid

import (
	"encoding/json"
	"time"
)

// CraReportGetHomeLendingMetadata Home Lending report metadata returned by `/cra/report/get`.
type CraReportGetHomeLendingMetadata struct {
	// The time the report was generated. May be `null` if unavailable.
	GeneratedTime NullableTime `json:"generated_time"`
	// The number of Items used to generate the report.
	ItemCount int32 `json:"item_count"`
	// The number of accounts used to generate the report.
	AccountCount int32 `json:"account_count"`
	// The institution IDs of the Items used to generate the report.
	InstitutionIds []string `json:"institution_ids"`
	AdditionalProperties map[string]interface{}
}

type _CraReportGetHomeLendingMetadata CraReportGetHomeLendingMetadata

// NewCraReportGetHomeLendingMetadata instantiates a new CraReportGetHomeLendingMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCraReportGetHomeLendingMetadata(generatedTime NullableTime, itemCount int32, accountCount int32, institutionIds []string) *CraReportGetHomeLendingMetadata {
	this := CraReportGetHomeLendingMetadata{}
	this.GeneratedTime = generatedTime
	this.ItemCount = itemCount
	this.AccountCount = accountCount
	this.InstitutionIds = institutionIds
	return &this
}

// NewCraReportGetHomeLendingMetadataWithDefaults instantiates a new CraReportGetHomeLendingMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCraReportGetHomeLendingMetadataWithDefaults() *CraReportGetHomeLendingMetadata {
	this := CraReportGetHomeLendingMetadata{}
	return &this
}

// GetGeneratedTime returns the GeneratedTime field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *CraReportGetHomeLendingMetadata) GetGeneratedTime() time.Time {
	if o == nil || o.GeneratedTime.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.GeneratedTime.Get()
}

// GetGeneratedTimeOk returns a tuple with the GeneratedTime field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CraReportGetHomeLendingMetadata) GetGeneratedTimeOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.GeneratedTime.Get(), o.GeneratedTime.IsSet()
}

// SetGeneratedTime sets field value
func (o *CraReportGetHomeLendingMetadata) SetGeneratedTime(v time.Time) {
	o.GeneratedTime.Set(&v)
}

// GetItemCount returns the ItemCount field value
func (o *CraReportGetHomeLendingMetadata) GetItemCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ItemCount
}

// GetItemCountOk returns a tuple with the ItemCount field value
// and a boolean to check if the value has been set.
func (o *CraReportGetHomeLendingMetadata) GetItemCountOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ItemCount, true
}

// SetItemCount sets field value
func (o *CraReportGetHomeLendingMetadata) SetItemCount(v int32) {
	o.ItemCount = v
}

// GetAccountCount returns the AccountCount field value
func (o *CraReportGetHomeLendingMetadata) GetAccountCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AccountCount
}

// GetAccountCountOk returns a tuple with the AccountCount field value
// and a boolean to check if the value has been set.
func (o *CraReportGetHomeLendingMetadata) GetAccountCountOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AccountCount, true
}

// SetAccountCount sets field value
func (o *CraReportGetHomeLendingMetadata) SetAccountCount(v int32) {
	o.AccountCount = v
}

// GetInstitutionIds returns the InstitutionIds field value
func (o *CraReportGetHomeLendingMetadata) GetInstitutionIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.InstitutionIds
}

// GetInstitutionIdsOk returns a tuple with the InstitutionIds field value
// and a boolean to check if the value has been set.
func (o *CraReportGetHomeLendingMetadata) GetInstitutionIdsOk() (*[]string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.InstitutionIds, true
}

// SetInstitutionIds sets field value
func (o *CraReportGetHomeLendingMetadata) SetInstitutionIds(v []string) {
	o.InstitutionIds = v
}

func (o CraReportGetHomeLendingMetadata) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["generated_time"] = o.GeneratedTime.Get()
	}
	if true {
		toSerialize["item_count"] = o.ItemCount
	}
	if true {
		toSerialize["account_count"] = o.AccountCount
	}
	if true {
		toSerialize["institution_ids"] = o.InstitutionIds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *CraReportGetHomeLendingMetadata) UnmarshalJSON(bytes []byte) (err error) {
	varCraReportGetHomeLendingMetadata := _CraReportGetHomeLendingMetadata{}

	if err = json.Unmarshal(bytes, &varCraReportGetHomeLendingMetadata); err == nil {
		*o = CraReportGetHomeLendingMetadata(varCraReportGetHomeLendingMetadata)
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "generated_time")
		delete(additionalProperties, "item_count")
		delete(additionalProperties, "account_count")
		delete(additionalProperties, "institution_ids")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCraReportGetHomeLendingMetadata struct {
	value *CraReportGetHomeLendingMetadata
	isSet bool
}

func (v NullableCraReportGetHomeLendingMetadata) Get() *CraReportGetHomeLendingMetadata {
	return v.value
}

func (v *NullableCraReportGetHomeLendingMetadata) Set(val *CraReportGetHomeLendingMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableCraReportGetHomeLendingMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableCraReportGetHomeLendingMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCraReportGetHomeLendingMetadata(val *CraReportGetHomeLendingMetadata) *NullableCraReportGetHomeLendingMetadata {
	return &NullableCraReportGetHomeLendingMetadata{value: val, isSet: true}
}

func (v NullableCraReportGetHomeLendingMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCraReportGetHomeLendingMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


