/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * API version: 2020-09-14_1.762.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plaid

import (
	"encoding/json"
	"fmt"
)

// CraReportErrorCode The reason every product in a CRA report failed to generate. `null` when at least one product succeeded.  `DATA_UNAVAILABLE`: Plaid could not retrieve enough data from the user's Items to generate any of the requested products. Sending the user through Link to add or repair Items may resolve this.  `INTERNAL_SERVER_ERROR`: Plaid encountered an unexpected error while generating the report.
type CraReportErrorCode string

var _ = fmt.Printf

// List of CraReportErrorCode
const (
	CRAREPORTERRORCODE_DATA_UNAVAILABLE CraReportErrorCode = "DATA_UNAVAILABLE"
	CRAREPORTERRORCODE_INTERNAL_SERVER_ERROR CraReportErrorCode = "INTERNAL_SERVER_ERROR"
	CRAREPORTERRORCODE_NULL CraReportErrorCode = "null"
)

var allowedCraReportErrorCodeEnumValues = []CraReportErrorCode{
	"DATA_UNAVAILABLE",
	"INTERNAL_SERVER_ERROR",
	"null",
}

func (v *CraReportErrorCode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}

	enumTypeValue := CraReportErrorCode(value)


	*v = enumTypeValue
	return nil
}

// NewCraReportErrorCodeFromValue returns a pointer to a valid CraReportErrorCode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCraReportErrorCodeFromValue(v string) (*CraReportErrorCode, error) {
	ev := CraReportErrorCode(v)


	return &ev, nil
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CraReportErrorCode) IsValid() bool {
	for _, existing := range allowedCraReportErrorCodeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CraReportErrorCode value
func (v CraReportErrorCode) Ptr() *CraReportErrorCode {
	return &v
}

type NullableCraReportErrorCode struct {
	value *CraReportErrorCode
	isSet bool
}

func (v NullableCraReportErrorCode) Get() *CraReportErrorCode {
	return v.value
}

func (v *NullableCraReportErrorCode) Set(val *CraReportErrorCode) {
	v.value = val
	v.isSet = true
}

func (v NullableCraReportErrorCode) IsSet() bool {
	return v.isSet
}

func (v *NullableCraReportErrorCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCraReportErrorCode(val *CraReportErrorCode) *NullableCraReportErrorCode {
	return &NullableCraReportErrorCode{value: val, isSet: true}
}

func (v NullableCraReportErrorCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCraReportErrorCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

