/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * API version: 2020-09-14_1.610.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plaid

import (
	"encoding/json"
)

// KYCCheckNameSummary Result summary object specifying how the `name` field matched.
type KYCCheckNameSummary struct {
	Summary MatchSummaryCode `json:"summary"`
	GivenName *HiddenMatchSummaryCode `json:"given_name,omitempty"`
	FamilyName *HiddenMatchSummaryCode `json:"family_name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _KYCCheckNameSummary KYCCheckNameSummary

// NewKYCCheckNameSummary instantiates a new KYCCheckNameSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKYCCheckNameSummary(summary MatchSummaryCode) *KYCCheckNameSummary {
	this := KYCCheckNameSummary{}
	this.Summary = summary
	return &this
}

// NewKYCCheckNameSummaryWithDefaults instantiates a new KYCCheckNameSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKYCCheckNameSummaryWithDefaults() *KYCCheckNameSummary {
	this := KYCCheckNameSummary{}
	return &this
}

// GetSummary returns the Summary field value
func (o *KYCCheckNameSummary) GetSummary() MatchSummaryCode {
	if o == nil {
		var ret MatchSummaryCode
		return ret
	}

	return o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value
// and a boolean to check if the value has been set.
func (o *KYCCheckNameSummary) GetSummaryOk() (*MatchSummaryCode, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Summary, true
}

// SetSummary sets field value
func (o *KYCCheckNameSummary) SetSummary(v MatchSummaryCode) {
	o.Summary = v
}

// GetGivenName returns the GivenName field value if set, zero value otherwise.
func (o *KYCCheckNameSummary) GetGivenName() HiddenMatchSummaryCode {
	if o == nil || o.GivenName == nil {
		var ret HiddenMatchSummaryCode
		return ret
	}
	return *o.GivenName
}

// GetGivenNameOk returns a tuple with the GivenName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KYCCheckNameSummary) GetGivenNameOk() (*HiddenMatchSummaryCode, bool) {
	if o == nil || o.GivenName == nil {
		return nil, false
	}
	return o.GivenName, true
}

// HasGivenName returns a boolean if a field has been set.
func (o *KYCCheckNameSummary) HasGivenName() bool {
	if o != nil && o.GivenName != nil {
		return true
	}

	return false
}

// SetGivenName gets a reference to the given HiddenMatchSummaryCode and assigns it to the GivenName field.
func (o *KYCCheckNameSummary) SetGivenName(v HiddenMatchSummaryCode) {
	o.GivenName = &v
}

// GetFamilyName returns the FamilyName field value if set, zero value otherwise.
func (o *KYCCheckNameSummary) GetFamilyName() HiddenMatchSummaryCode {
	if o == nil || o.FamilyName == nil {
		var ret HiddenMatchSummaryCode
		return ret
	}
	return *o.FamilyName
}

// GetFamilyNameOk returns a tuple with the FamilyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KYCCheckNameSummary) GetFamilyNameOk() (*HiddenMatchSummaryCode, bool) {
	if o == nil || o.FamilyName == nil {
		return nil, false
	}
	return o.FamilyName, true
}

// HasFamilyName returns a boolean if a field has been set.
func (o *KYCCheckNameSummary) HasFamilyName() bool {
	if o != nil && o.FamilyName != nil {
		return true
	}

	return false
}

// SetFamilyName gets a reference to the given HiddenMatchSummaryCode and assigns it to the FamilyName field.
func (o *KYCCheckNameSummary) SetFamilyName(v HiddenMatchSummaryCode) {
	o.FamilyName = &v
}

func (o KYCCheckNameSummary) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["summary"] = o.Summary
	}
	if o.GivenName != nil {
		toSerialize["given_name"] = o.GivenName
	}
	if o.FamilyName != nil {
		toSerialize["family_name"] = o.FamilyName
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *KYCCheckNameSummary) UnmarshalJSON(bytes []byte) (err error) {
	varKYCCheckNameSummary := _KYCCheckNameSummary{}

	if err = json.Unmarshal(bytes, &varKYCCheckNameSummary); err == nil {
		*o = KYCCheckNameSummary(varKYCCheckNameSummary)
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "summary")
		delete(additionalProperties, "given_name")
		delete(additionalProperties, "family_name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableKYCCheckNameSummary struct {
	value *KYCCheckNameSummary
	isSet bool
}

func (v NullableKYCCheckNameSummary) Get() *KYCCheckNameSummary {
	return v.value
}

func (v *NullableKYCCheckNameSummary) Set(val *KYCCheckNameSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableKYCCheckNameSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableKYCCheckNameSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKYCCheckNameSummary(val *KYCCheckNameSummary) *NullableKYCCheckNameSummary {
	return &NullableKYCCheckNameSummary{value: val, isSet: true}
}

func (v NullableKYCCheckNameSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKYCCheckNameSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


