/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * API version: 2020-09-14_1.729.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plaid

import (
	"encoding/json"
)

// CashAdvanceRepayment The repayment details for a cash-advance.
type CashAdvanceRepayment struct {
	// The amount a user paid.
	AmountPaid Amount `json:"amount_paid"`
	// The amount a user is required to pay, including any fees or additional amounts.
	AmountDue Amount `json:"amount_due"`
	// The date the cash-advance is due, in ISO 8601 format (`YYYY-MM-DD`).
	DueDate string `json:"due_date"`
	AdditionalProperties map[string]interface{}
}

type _CashAdvanceRepayment CashAdvanceRepayment

// NewCashAdvanceRepayment instantiates a new CashAdvanceRepayment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCashAdvanceRepayment(amountPaid Amount, amountDue Amount, dueDate string) *CashAdvanceRepayment {
	this := CashAdvanceRepayment{}
	this.AmountPaid = amountPaid
	this.AmountDue = amountDue
	this.DueDate = dueDate
	return &this
}

// NewCashAdvanceRepaymentWithDefaults instantiates a new CashAdvanceRepayment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCashAdvanceRepaymentWithDefaults() *CashAdvanceRepayment {
	this := CashAdvanceRepayment{}
	return &this
}

// GetAmountPaid returns the AmountPaid field value
func (o *CashAdvanceRepayment) GetAmountPaid() Amount {
	if o == nil {
		var ret Amount
		return ret
	}

	return o.AmountPaid
}

// GetAmountPaidOk returns a tuple with the AmountPaid field value
// and a boolean to check if the value has been set.
func (o *CashAdvanceRepayment) GetAmountPaidOk() (*Amount, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AmountPaid, true
}

// SetAmountPaid sets field value
func (o *CashAdvanceRepayment) SetAmountPaid(v Amount) {
	o.AmountPaid = v
}

// GetAmountDue returns the AmountDue field value
func (o *CashAdvanceRepayment) GetAmountDue() Amount {
	if o == nil {
		var ret Amount
		return ret
	}

	return o.AmountDue
}

// GetAmountDueOk returns a tuple with the AmountDue field value
// and a boolean to check if the value has been set.
func (o *CashAdvanceRepayment) GetAmountDueOk() (*Amount, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AmountDue, true
}

// SetAmountDue sets field value
func (o *CashAdvanceRepayment) SetAmountDue(v Amount) {
	o.AmountDue = v
}

// GetDueDate returns the DueDate field value
func (o *CashAdvanceRepayment) GetDueDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DueDate
}

// GetDueDateOk returns a tuple with the DueDate field value
// and a boolean to check if the value has been set.
func (o *CashAdvanceRepayment) GetDueDateOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DueDate, true
}

// SetDueDate sets field value
func (o *CashAdvanceRepayment) SetDueDate(v string) {
	o.DueDate = v
}

func (o CashAdvanceRepayment) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["amount_paid"] = o.AmountPaid
	}
	if true {
		toSerialize["amount_due"] = o.AmountDue
	}
	if true {
		toSerialize["due_date"] = o.DueDate
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *CashAdvanceRepayment) UnmarshalJSON(bytes []byte) (err error) {
	varCashAdvanceRepayment := _CashAdvanceRepayment{}

	if err = json.Unmarshal(bytes, &varCashAdvanceRepayment); err == nil {
		*o = CashAdvanceRepayment(varCashAdvanceRepayment)
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "amount_paid")
		delete(additionalProperties, "amount_due")
		delete(additionalProperties, "due_date")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCashAdvanceRepayment struct {
	value *CashAdvanceRepayment
	isSet bool
}

func (v NullableCashAdvanceRepayment) Get() *CashAdvanceRepayment {
	return v.value
}

func (v *NullableCashAdvanceRepayment) Set(val *CashAdvanceRepayment) {
	v.value = val
	v.isSet = true
}

func (v NullableCashAdvanceRepayment) IsSet() bool {
	return v.isSet
}

func (v *NullableCashAdvanceRepayment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCashAdvanceRepayment(val *CashAdvanceRepayment) *NullableCashAdvanceRepayment {
	return &NullableCashAdvanceRepayment{value: val, isSet: true}
}

func (v NullableCashAdvanceRepayment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCashAdvanceRepayment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


