/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * API version: 2020-09-14_1.641.1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plaid

import (
	"encoding/json"
)

// IdentityVerificationDocumentNameResponse The individual's name extracted from the document.
type IdentityVerificationDocumentNameResponse struct {
	// A string with at least one non-whitespace character, with a max length of 100 characters.
	GivenName string `json:"given_name"`
	// A string with at least one non-whitespace character, with a max length of 100 characters.
	FamilyName string `json:"family_name"`
	AdditionalProperties map[string]interface{}
}

type _IdentityVerificationDocumentNameResponse IdentityVerificationDocumentNameResponse

// NewIdentityVerificationDocumentNameResponse instantiates a new IdentityVerificationDocumentNameResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdentityVerificationDocumentNameResponse(givenName string, familyName string) *IdentityVerificationDocumentNameResponse {
	this := IdentityVerificationDocumentNameResponse{}
	this.GivenName = givenName
	this.FamilyName = familyName
	return &this
}

// NewIdentityVerificationDocumentNameResponseWithDefaults instantiates a new IdentityVerificationDocumentNameResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentityVerificationDocumentNameResponseWithDefaults() *IdentityVerificationDocumentNameResponse {
	this := IdentityVerificationDocumentNameResponse{}
	return &this
}

// GetGivenName returns the GivenName field value
func (o *IdentityVerificationDocumentNameResponse) GetGivenName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GivenName
}

// GetGivenNameOk returns a tuple with the GivenName field value
// and a boolean to check if the value has been set.
func (o *IdentityVerificationDocumentNameResponse) GetGivenNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.GivenName, true
}

// SetGivenName sets field value
func (o *IdentityVerificationDocumentNameResponse) SetGivenName(v string) {
	o.GivenName = v
}

// GetFamilyName returns the FamilyName field value
func (o *IdentityVerificationDocumentNameResponse) GetFamilyName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FamilyName
}

// GetFamilyNameOk returns a tuple with the FamilyName field value
// and a boolean to check if the value has been set.
func (o *IdentityVerificationDocumentNameResponse) GetFamilyNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.FamilyName, true
}

// SetFamilyName sets field value
func (o *IdentityVerificationDocumentNameResponse) SetFamilyName(v string) {
	o.FamilyName = v
}

func (o IdentityVerificationDocumentNameResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["given_name"] = o.GivenName
	}
	if true {
		toSerialize["family_name"] = o.FamilyName
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *IdentityVerificationDocumentNameResponse) UnmarshalJSON(bytes []byte) (err error) {
	varIdentityVerificationDocumentNameResponse := _IdentityVerificationDocumentNameResponse{}

	if err = json.Unmarshal(bytes, &varIdentityVerificationDocumentNameResponse); err == nil {
		*o = IdentityVerificationDocumentNameResponse(varIdentityVerificationDocumentNameResponse)
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "given_name")
		delete(additionalProperties, "family_name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIdentityVerificationDocumentNameResponse struct {
	value *IdentityVerificationDocumentNameResponse
	isSet bool
}

func (v NullableIdentityVerificationDocumentNameResponse) Get() *IdentityVerificationDocumentNameResponse {
	return v.value
}

func (v *NullableIdentityVerificationDocumentNameResponse) Set(val *IdentityVerificationDocumentNameResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentityVerificationDocumentNameResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentityVerificationDocumentNameResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentityVerificationDocumentNameResponse(val *IdentityVerificationDocumentNameResponse) *NullableIdentityVerificationDocumentNameResponse {
	return &NullableIdentityVerificationDocumentNameResponse{value: val, isSet: true}
}

func (v NullableIdentityVerificationDocumentNameResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentityVerificationDocumentNameResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


