/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * API version: 2020-09-14_1.197.3
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plaid

import (
	"encoding/json"
	"time"
)

// IdentityVerificationRetryResponse A identity verification attempt represents a customer's attempt to verify their identity, reflecting the required steps for completing the session, the results for each step, and information collected in the process.
type IdentityVerificationRetryResponse struct {
	// ID of the associated Identity Verification attempt.
	Id string `json:"id"`
	// An identifier to help you connect this object to your internal systems. For example, your database ID corresponding to this object.
	ClientUserId string `json:"client_user_id"`
	// An ISO8601 formatted timestamp.
	CreatedAt time.Time `json:"created_at"`
	// An ISO8601 formatted timestamp.
	CompletedAt NullableTime `json:"completed_at"`
	// The ID for the Identity Verification preceding this session. This field will only be filled if the current Identity Verification is a retry of a previous attempt.
	PreviousAttemptId NullableString `json:"previous_attempt_id"`
	// A shareable URL that can be sent directly to the user to complete verification
	ShareableUrl NullableString `json:"shareable_url"`
	Template IdentityVerificationTemplateReference `json:"template"`
	User IdentityVerificationUserData `json:"user"`
	Status IdentityVerificationStatus `json:"status"`
	Steps IdentityVerificationStepSummary `json:"steps"`
	DocumentaryVerification NullableDocumentaryVerification `json:"documentary_verification"`
	KycCheck NullableKYCCheckDetails `json:"kyc_check"`
	// ID of the associated screening.
	WatchlistScreeningId NullableString `json:"watchlist_screening_id"`
	// A unique identifier for the request, which can be used for troubleshooting. This identifier, like all Plaid identifiers, is case sensitive.
	RequestId string `json:"request_id"`
	AdditionalProperties map[string]interface{}
}

type _IdentityVerificationRetryResponse IdentityVerificationRetryResponse

// NewIdentityVerificationRetryResponse instantiates a new IdentityVerificationRetryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdentityVerificationRetryResponse(id string, clientUserId string, createdAt time.Time, completedAt NullableTime, previousAttemptId NullableString, shareableUrl NullableString, template IdentityVerificationTemplateReference, user IdentityVerificationUserData, status IdentityVerificationStatus, steps IdentityVerificationStepSummary, documentaryVerification NullableDocumentaryVerification, kycCheck NullableKYCCheckDetails, watchlistScreeningId NullableString, requestId string) *IdentityVerificationRetryResponse {
	this := IdentityVerificationRetryResponse{}
	this.Id = id
	this.ClientUserId = clientUserId
	this.CreatedAt = createdAt
	this.CompletedAt = completedAt
	this.PreviousAttemptId = previousAttemptId
	this.ShareableUrl = shareableUrl
	this.Template = template
	this.User = user
	this.Status = status
	this.Steps = steps
	this.DocumentaryVerification = documentaryVerification
	this.KycCheck = kycCheck
	this.WatchlistScreeningId = watchlistScreeningId
	this.RequestId = requestId
	return &this
}

// NewIdentityVerificationRetryResponseWithDefaults instantiates a new IdentityVerificationRetryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentityVerificationRetryResponseWithDefaults() *IdentityVerificationRetryResponse {
	this := IdentityVerificationRetryResponse{}
	return &this
}

// GetId returns the Id field value
func (o *IdentityVerificationRetryResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *IdentityVerificationRetryResponse) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *IdentityVerificationRetryResponse) SetId(v string) {
	o.Id = v
}

// GetClientUserId returns the ClientUserId field value
func (o *IdentityVerificationRetryResponse) GetClientUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientUserId
}

// GetClientUserIdOk returns a tuple with the ClientUserId field value
// and a boolean to check if the value has been set.
func (o *IdentityVerificationRetryResponse) GetClientUserIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ClientUserId, true
}

// SetClientUserId sets field value
func (o *IdentityVerificationRetryResponse) SetClientUserId(v string) {
	o.ClientUserId = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *IdentityVerificationRetryResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *IdentityVerificationRetryResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *IdentityVerificationRetryResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetCompletedAt returns the CompletedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *IdentityVerificationRetryResponse) GetCompletedAt() time.Time {
	if o == nil || o.CompletedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.CompletedAt.Get()
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IdentityVerificationRetryResponse) GetCompletedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.CompletedAt.Get(), o.CompletedAt.IsSet()
}

// SetCompletedAt sets field value
func (o *IdentityVerificationRetryResponse) SetCompletedAt(v time.Time) {
	o.CompletedAt.Set(&v)
}

// GetPreviousAttemptId returns the PreviousAttemptId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *IdentityVerificationRetryResponse) GetPreviousAttemptId() string {
	if o == nil || o.PreviousAttemptId.Get() == nil {
		var ret string
		return ret
	}

	return *o.PreviousAttemptId.Get()
}

// GetPreviousAttemptIdOk returns a tuple with the PreviousAttemptId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IdentityVerificationRetryResponse) GetPreviousAttemptIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.PreviousAttemptId.Get(), o.PreviousAttemptId.IsSet()
}

// SetPreviousAttemptId sets field value
func (o *IdentityVerificationRetryResponse) SetPreviousAttemptId(v string) {
	o.PreviousAttemptId.Set(&v)
}

// GetShareableUrl returns the ShareableUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *IdentityVerificationRetryResponse) GetShareableUrl() string {
	if o == nil || o.ShareableUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.ShareableUrl.Get()
}

// GetShareableUrlOk returns a tuple with the ShareableUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IdentityVerificationRetryResponse) GetShareableUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ShareableUrl.Get(), o.ShareableUrl.IsSet()
}

// SetShareableUrl sets field value
func (o *IdentityVerificationRetryResponse) SetShareableUrl(v string) {
	o.ShareableUrl.Set(&v)
}

// GetTemplate returns the Template field value
func (o *IdentityVerificationRetryResponse) GetTemplate() IdentityVerificationTemplateReference {
	if o == nil {
		var ret IdentityVerificationTemplateReference
		return ret
	}

	return o.Template
}

// GetTemplateOk returns a tuple with the Template field value
// and a boolean to check if the value has been set.
func (o *IdentityVerificationRetryResponse) GetTemplateOk() (*IdentityVerificationTemplateReference, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Template, true
}

// SetTemplate sets field value
func (o *IdentityVerificationRetryResponse) SetTemplate(v IdentityVerificationTemplateReference) {
	o.Template = v
}

// GetUser returns the User field value
func (o *IdentityVerificationRetryResponse) GetUser() IdentityVerificationUserData {
	if o == nil {
		var ret IdentityVerificationUserData
		return ret
	}

	return o.User
}

// GetUserOk returns a tuple with the User field value
// and a boolean to check if the value has been set.
func (o *IdentityVerificationRetryResponse) GetUserOk() (*IdentityVerificationUserData, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.User, true
}

// SetUser sets field value
func (o *IdentityVerificationRetryResponse) SetUser(v IdentityVerificationUserData) {
	o.User = v
}

// GetStatus returns the Status field value
func (o *IdentityVerificationRetryResponse) GetStatus() IdentityVerificationStatus {
	if o == nil {
		var ret IdentityVerificationStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *IdentityVerificationRetryResponse) GetStatusOk() (*IdentityVerificationStatus, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *IdentityVerificationRetryResponse) SetStatus(v IdentityVerificationStatus) {
	o.Status = v
}

// GetSteps returns the Steps field value
func (o *IdentityVerificationRetryResponse) GetSteps() IdentityVerificationStepSummary {
	if o == nil {
		var ret IdentityVerificationStepSummary
		return ret
	}

	return o.Steps
}

// GetStepsOk returns a tuple with the Steps field value
// and a boolean to check if the value has been set.
func (o *IdentityVerificationRetryResponse) GetStepsOk() (*IdentityVerificationStepSummary, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Steps, true
}

// SetSteps sets field value
func (o *IdentityVerificationRetryResponse) SetSteps(v IdentityVerificationStepSummary) {
	o.Steps = v
}

// GetDocumentaryVerification returns the DocumentaryVerification field value
// If the value is explicit nil, the zero value for DocumentaryVerification will be returned
func (o *IdentityVerificationRetryResponse) GetDocumentaryVerification() DocumentaryVerification {
	if o == nil || o.DocumentaryVerification.Get() == nil {
		var ret DocumentaryVerification
		return ret
	}

	return *o.DocumentaryVerification.Get()
}

// GetDocumentaryVerificationOk returns a tuple with the DocumentaryVerification field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IdentityVerificationRetryResponse) GetDocumentaryVerificationOk() (*DocumentaryVerification, bool) {
	if o == nil  {
		return nil, false
	}
	return o.DocumentaryVerification.Get(), o.DocumentaryVerification.IsSet()
}

// SetDocumentaryVerification sets field value
func (o *IdentityVerificationRetryResponse) SetDocumentaryVerification(v DocumentaryVerification) {
	o.DocumentaryVerification.Set(&v)
}

// GetKycCheck returns the KycCheck field value
// If the value is explicit nil, the zero value for KYCCheckDetails will be returned
func (o *IdentityVerificationRetryResponse) GetKycCheck() KYCCheckDetails {
	if o == nil || o.KycCheck.Get() == nil {
		var ret KYCCheckDetails
		return ret
	}

	return *o.KycCheck.Get()
}

// GetKycCheckOk returns a tuple with the KycCheck field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IdentityVerificationRetryResponse) GetKycCheckOk() (*KYCCheckDetails, bool) {
	if o == nil  {
		return nil, false
	}
	return o.KycCheck.Get(), o.KycCheck.IsSet()
}

// SetKycCheck sets field value
func (o *IdentityVerificationRetryResponse) SetKycCheck(v KYCCheckDetails) {
	o.KycCheck.Set(&v)
}

// GetWatchlistScreeningId returns the WatchlistScreeningId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *IdentityVerificationRetryResponse) GetWatchlistScreeningId() string {
	if o == nil || o.WatchlistScreeningId.Get() == nil {
		var ret string
		return ret
	}

	return *o.WatchlistScreeningId.Get()
}

// GetWatchlistScreeningIdOk returns a tuple with the WatchlistScreeningId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IdentityVerificationRetryResponse) GetWatchlistScreeningIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.WatchlistScreeningId.Get(), o.WatchlistScreeningId.IsSet()
}

// SetWatchlistScreeningId sets field value
func (o *IdentityVerificationRetryResponse) SetWatchlistScreeningId(v string) {
	o.WatchlistScreeningId.Set(&v)
}

// GetRequestId returns the RequestId field value
func (o *IdentityVerificationRetryResponse) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *IdentityVerificationRetryResponse) GetRequestIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *IdentityVerificationRetryResponse) SetRequestId(v string) {
	o.RequestId = v
}

func (o IdentityVerificationRetryResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["client_user_id"] = o.ClientUserId
	}
	if true {
		toSerialize["created_at"] = o.CreatedAt
	}
	if true {
		toSerialize["completed_at"] = o.CompletedAt.Get()
	}
	if true {
		toSerialize["previous_attempt_id"] = o.PreviousAttemptId.Get()
	}
	if true {
		toSerialize["shareable_url"] = o.ShareableUrl.Get()
	}
	if true {
		toSerialize["template"] = o.Template
	}
	if true {
		toSerialize["user"] = o.User
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if true {
		toSerialize["steps"] = o.Steps
	}
	if true {
		toSerialize["documentary_verification"] = o.DocumentaryVerification.Get()
	}
	if true {
		toSerialize["kyc_check"] = o.KycCheck.Get()
	}
	if true {
		toSerialize["watchlist_screening_id"] = o.WatchlistScreeningId.Get()
	}
	if true {
		toSerialize["request_id"] = o.RequestId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *IdentityVerificationRetryResponse) UnmarshalJSON(bytes []byte) (err error) {
	varIdentityVerificationRetryResponse := _IdentityVerificationRetryResponse{}

	if err = json.Unmarshal(bytes, &varIdentityVerificationRetryResponse); err == nil {
		*o = IdentityVerificationRetryResponse(varIdentityVerificationRetryResponse)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "client_user_id")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "completed_at")
		delete(additionalProperties, "previous_attempt_id")
		delete(additionalProperties, "shareable_url")
		delete(additionalProperties, "template")
		delete(additionalProperties, "user")
		delete(additionalProperties, "status")
		delete(additionalProperties, "steps")
		delete(additionalProperties, "documentary_verification")
		delete(additionalProperties, "kyc_check")
		delete(additionalProperties, "watchlist_screening_id")
		delete(additionalProperties, "request_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIdentityVerificationRetryResponse struct {
	value *IdentityVerificationRetryResponse
	isSet bool
}

func (v NullableIdentityVerificationRetryResponse) Get() *IdentityVerificationRetryResponse {
	return v.value
}

func (v *NullableIdentityVerificationRetryResponse) Set(val *IdentityVerificationRetryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentityVerificationRetryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentityVerificationRetryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentityVerificationRetryResponse(val *IdentityVerificationRetryResponse) *NullableIdentityVerificationRetryResponse {
	return &NullableIdentityVerificationRetryResponse{value: val, isSet: true}
}

func (v NullableIdentityVerificationRetryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentityVerificationRetryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


