/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * API version: 2020-09-14_1.680.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plaid

import (
	"encoding/json"
)

// LoanDisbursementsIndicators Insights into loan disbursement transactions received by the user, tracking incoming funds from loan providers.
type LoanDisbursementsIndicators struct {
	// The total value of inflow transactions categorized as `LOAN_DISBURSEMENTS`, across all the accounts in the report within the requested time window.
	Amount NullableFloat64 `json:"amount,omitempty"`
	// The ISO-4217 currency code of the amount. Always `null` if `unofficial_currency_code` is non-`null`.
	IsoCurrencyCode NullableString `json:"iso_currency_code,omitempty"`
	// The unofficial currency code associated with the amount. Always `null` if `iso_currency_code` is non-`null`.  See the [currency code schema](https://plaid.com/docs/api/accounts#currency-code-schema) for a full listing of supported `unofficial_currency_code`s.
	UnofficialCurrencyCode NullableString `json:"unofficial_currency_code,omitempty"`
	// Detailed categories view of all the transactions that fall into the `LOAN_DISBURSEMENTS` credit category within the given time window, across all the accounts in the report.
	CategoryDetails *[]CategoryExpenses `json:"category_details,omitempty"`
	MonthlyAverage NullableMonthlyAverage `json:"monthly_average,omitempty"`
	// Up to 3 top service providers that the user had the most transactions for in the given time window, in descending order of total spend.  If the user has received money from any provider in the given time window, this list will be empty.
	TopProviders *[]string `json:"top_providers,omitempty"`
	// The total number of transactions that fall into the `LOAN_DISBURSEMENTS` credit category, across all the accounts in the report.
	TransactionsCount NullableInt32 `json:"transactions_count,omitempty"`
	// The monthly summaries of the transactions that fall into the `LOAN_DISBURSEMENTS` category within the given time window, across all the accounts in the report.
	MonthlySummaries *[]MonthlySummary `json:"monthly_summaries,omitempty"`
	// The number of days since the last transaction that falls into the `LOAN_DISBURSEMENTS` credit category, across all the accounts in the report.
	DaysSinceLastOccurrence NullableInt32 `json:"days_since_last_occurrence,omitempty"`
	// The percentage of the user's monthly inflows that was received on transactions that fall into the `LOAN_DISBURSEMENTS` credit category within the given time window, across all the accounts in the report. For example, a value of 100 indicates that 100% of the inflows were spent on transactions that fall into the `LOAN_DISBURSEMENTS` credit category. If there's no available income for the given time period, this field value will be `-1`.
	PercentageOfIncome NullableFloat64 `json:"percentage_of_income,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _LoanDisbursementsIndicators LoanDisbursementsIndicators

// NewLoanDisbursementsIndicators instantiates a new LoanDisbursementsIndicators object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoanDisbursementsIndicators() *LoanDisbursementsIndicators {
	this := LoanDisbursementsIndicators{}
	return &this
}

// NewLoanDisbursementsIndicatorsWithDefaults instantiates a new LoanDisbursementsIndicators object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoanDisbursementsIndicatorsWithDefaults() *LoanDisbursementsIndicators {
	this := LoanDisbursementsIndicators{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LoanDisbursementsIndicators) GetAmount() float64 {
	if o == nil || o.Amount.Get() == nil {
		var ret float64
		return ret
	}
	return *o.Amount.Get()
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LoanDisbursementsIndicators) GetAmountOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Amount.Get(), o.Amount.IsSet()
}

// HasAmount returns a boolean if a field has been set.
func (o *LoanDisbursementsIndicators) HasAmount() bool {
	if o != nil && o.Amount.IsSet() {
		return true
	}

	return false
}

// SetAmount gets a reference to the given NullableFloat64 and assigns it to the Amount field.
func (o *LoanDisbursementsIndicators) SetAmount(v float64) {
	o.Amount.Set(&v)
}
// SetAmountNil sets the value for Amount to be an explicit nil
func (o *LoanDisbursementsIndicators) SetAmountNil() {
	o.Amount.Set(nil)
}

// UnsetAmount ensures that no value is present for Amount, not even an explicit nil
func (o *LoanDisbursementsIndicators) UnsetAmount() {
	o.Amount.Unset()
}

// GetIsoCurrencyCode returns the IsoCurrencyCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LoanDisbursementsIndicators) GetIsoCurrencyCode() string {
	if o == nil || o.IsoCurrencyCode.Get() == nil {
		var ret string
		return ret
	}
	return *o.IsoCurrencyCode.Get()
}

// GetIsoCurrencyCodeOk returns a tuple with the IsoCurrencyCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LoanDisbursementsIndicators) GetIsoCurrencyCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.IsoCurrencyCode.Get(), o.IsoCurrencyCode.IsSet()
}

// HasIsoCurrencyCode returns a boolean if a field has been set.
func (o *LoanDisbursementsIndicators) HasIsoCurrencyCode() bool {
	if o != nil && o.IsoCurrencyCode.IsSet() {
		return true
	}

	return false
}

// SetIsoCurrencyCode gets a reference to the given NullableString and assigns it to the IsoCurrencyCode field.
func (o *LoanDisbursementsIndicators) SetIsoCurrencyCode(v string) {
	o.IsoCurrencyCode.Set(&v)
}
// SetIsoCurrencyCodeNil sets the value for IsoCurrencyCode to be an explicit nil
func (o *LoanDisbursementsIndicators) SetIsoCurrencyCodeNil() {
	o.IsoCurrencyCode.Set(nil)
}

// UnsetIsoCurrencyCode ensures that no value is present for IsoCurrencyCode, not even an explicit nil
func (o *LoanDisbursementsIndicators) UnsetIsoCurrencyCode() {
	o.IsoCurrencyCode.Unset()
}

// GetUnofficialCurrencyCode returns the UnofficialCurrencyCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LoanDisbursementsIndicators) GetUnofficialCurrencyCode() string {
	if o == nil || o.UnofficialCurrencyCode.Get() == nil {
		var ret string
		return ret
	}
	return *o.UnofficialCurrencyCode.Get()
}

// GetUnofficialCurrencyCodeOk returns a tuple with the UnofficialCurrencyCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LoanDisbursementsIndicators) GetUnofficialCurrencyCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.UnofficialCurrencyCode.Get(), o.UnofficialCurrencyCode.IsSet()
}

// HasUnofficialCurrencyCode returns a boolean if a field has been set.
func (o *LoanDisbursementsIndicators) HasUnofficialCurrencyCode() bool {
	if o != nil && o.UnofficialCurrencyCode.IsSet() {
		return true
	}

	return false
}

// SetUnofficialCurrencyCode gets a reference to the given NullableString and assigns it to the UnofficialCurrencyCode field.
func (o *LoanDisbursementsIndicators) SetUnofficialCurrencyCode(v string) {
	o.UnofficialCurrencyCode.Set(&v)
}
// SetUnofficialCurrencyCodeNil sets the value for UnofficialCurrencyCode to be an explicit nil
func (o *LoanDisbursementsIndicators) SetUnofficialCurrencyCodeNil() {
	o.UnofficialCurrencyCode.Set(nil)
}

// UnsetUnofficialCurrencyCode ensures that no value is present for UnofficialCurrencyCode, not even an explicit nil
func (o *LoanDisbursementsIndicators) UnsetUnofficialCurrencyCode() {
	o.UnofficialCurrencyCode.Unset()
}

// GetCategoryDetails returns the CategoryDetails field value if set, zero value otherwise.
func (o *LoanDisbursementsIndicators) GetCategoryDetails() []CategoryExpenses {
	if o == nil || o.CategoryDetails == nil {
		var ret []CategoryExpenses
		return ret
	}
	return *o.CategoryDetails
}

// GetCategoryDetailsOk returns a tuple with the CategoryDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoanDisbursementsIndicators) GetCategoryDetailsOk() (*[]CategoryExpenses, bool) {
	if o == nil || o.CategoryDetails == nil {
		return nil, false
	}
	return o.CategoryDetails, true
}

// HasCategoryDetails returns a boolean if a field has been set.
func (o *LoanDisbursementsIndicators) HasCategoryDetails() bool {
	if o != nil && o.CategoryDetails != nil {
		return true
	}

	return false
}

// SetCategoryDetails gets a reference to the given []CategoryExpenses and assigns it to the CategoryDetails field.
func (o *LoanDisbursementsIndicators) SetCategoryDetails(v []CategoryExpenses) {
	o.CategoryDetails = &v
}

// GetMonthlyAverage returns the MonthlyAverage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LoanDisbursementsIndicators) GetMonthlyAverage() MonthlyAverage {
	if o == nil || o.MonthlyAverage.Get() == nil {
		var ret MonthlyAverage
		return ret
	}
	return *o.MonthlyAverage.Get()
}

// GetMonthlyAverageOk returns a tuple with the MonthlyAverage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LoanDisbursementsIndicators) GetMonthlyAverageOk() (*MonthlyAverage, bool) {
	if o == nil  {
		return nil, false
	}
	return o.MonthlyAverage.Get(), o.MonthlyAverage.IsSet()
}

// HasMonthlyAverage returns a boolean if a field has been set.
func (o *LoanDisbursementsIndicators) HasMonthlyAverage() bool {
	if o != nil && o.MonthlyAverage.IsSet() {
		return true
	}

	return false
}

// SetMonthlyAverage gets a reference to the given NullableMonthlyAverage and assigns it to the MonthlyAverage field.
func (o *LoanDisbursementsIndicators) SetMonthlyAverage(v MonthlyAverage) {
	o.MonthlyAverage.Set(&v)
}
// SetMonthlyAverageNil sets the value for MonthlyAverage to be an explicit nil
func (o *LoanDisbursementsIndicators) SetMonthlyAverageNil() {
	o.MonthlyAverage.Set(nil)
}

// UnsetMonthlyAverage ensures that no value is present for MonthlyAverage, not even an explicit nil
func (o *LoanDisbursementsIndicators) UnsetMonthlyAverage() {
	o.MonthlyAverage.Unset()
}

// GetTopProviders returns the TopProviders field value if set, zero value otherwise.
func (o *LoanDisbursementsIndicators) GetTopProviders() []string {
	if o == nil || o.TopProviders == nil {
		var ret []string
		return ret
	}
	return *o.TopProviders
}

// GetTopProvidersOk returns a tuple with the TopProviders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoanDisbursementsIndicators) GetTopProvidersOk() (*[]string, bool) {
	if o == nil || o.TopProviders == nil {
		return nil, false
	}
	return o.TopProviders, true
}

// HasTopProviders returns a boolean if a field has been set.
func (o *LoanDisbursementsIndicators) HasTopProviders() bool {
	if o != nil && o.TopProviders != nil {
		return true
	}

	return false
}

// SetTopProviders gets a reference to the given []string and assigns it to the TopProviders field.
func (o *LoanDisbursementsIndicators) SetTopProviders(v []string) {
	o.TopProviders = &v
}

// GetTransactionsCount returns the TransactionsCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LoanDisbursementsIndicators) GetTransactionsCount() int32 {
	if o == nil || o.TransactionsCount.Get() == nil {
		var ret int32
		return ret
	}
	return *o.TransactionsCount.Get()
}

// GetTransactionsCountOk returns a tuple with the TransactionsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LoanDisbursementsIndicators) GetTransactionsCountOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.TransactionsCount.Get(), o.TransactionsCount.IsSet()
}

// HasTransactionsCount returns a boolean if a field has been set.
func (o *LoanDisbursementsIndicators) HasTransactionsCount() bool {
	if o != nil && o.TransactionsCount.IsSet() {
		return true
	}

	return false
}

// SetTransactionsCount gets a reference to the given NullableInt32 and assigns it to the TransactionsCount field.
func (o *LoanDisbursementsIndicators) SetTransactionsCount(v int32) {
	o.TransactionsCount.Set(&v)
}
// SetTransactionsCountNil sets the value for TransactionsCount to be an explicit nil
func (o *LoanDisbursementsIndicators) SetTransactionsCountNil() {
	o.TransactionsCount.Set(nil)
}

// UnsetTransactionsCount ensures that no value is present for TransactionsCount, not even an explicit nil
func (o *LoanDisbursementsIndicators) UnsetTransactionsCount() {
	o.TransactionsCount.Unset()
}

// GetMonthlySummaries returns the MonthlySummaries field value if set, zero value otherwise.
func (o *LoanDisbursementsIndicators) GetMonthlySummaries() []MonthlySummary {
	if o == nil || o.MonthlySummaries == nil {
		var ret []MonthlySummary
		return ret
	}
	return *o.MonthlySummaries
}

// GetMonthlySummariesOk returns a tuple with the MonthlySummaries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoanDisbursementsIndicators) GetMonthlySummariesOk() (*[]MonthlySummary, bool) {
	if o == nil || o.MonthlySummaries == nil {
		return nil, false
	}
	return o.MonthlySummaries, true
}

// HasMonthlySummaries returns a boolean if a field has been set.
func (o *LoanDisbursementsIndicators) HasMonthlySummaries() bool {
	if o != nil && o.MonthlySummaries != nil {
		return true
	}

	return false
}

// SetMonthlySummaries gets a reference to the given []MonthlySummary and assigns it to the MonthlySummaries field.
func (o *LoanDisbursementsIndicators) SetMonthlySummaries(v []MonthlySummary) {
	o.MonthlySummaries = &v
}

// GetDaysSinceLastOccurrence returns the DaysSinceLastOccurrence field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LoanDisbursementsIndicators) GetDaysSinceLastOccurrence() int32 {
	if o == nil || o.DaysSinceLastOccurrence.Get() == nil {
		var ret int32
		return ret
	}
	return *o.DaysSinceLastOccurrence.Get()
}

// GetDaysSinceLastOccurrenceOk returns a tuple with the DaysSinceLastOccurrence field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LoanDisbursementsIndicators) GetDaysSinceLastOccurrenceOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.DaysSinceLastOccurrence.Get(), o.DaysSinceLastOccurrence.IsSet()
}

// HasDaysSinceLastOccurrence returns a boolean if a field has been set.
func (o *LoanDisbursementsIndicators) HasDaysSinceLastOccurrence() bool {
	if o != nil && o.DaysSinceLastOccurrence.IsSet() {
		return true
	}

	return false
}

// SetDaysSinceLastOccurrence gets a reference to the given NullableInt32 and assigns it to the DaysSinceLastOccurrence field.
func (o *LoanDisbursementsIndicators) SetDaysSinceLastOccurrence(v int32) {
	o.DaysSinceLastOccurrence.Set(&v)
}
// SetDaysSinceLastOccurrenceNil sets the value for DaysSinceLastOccurrence to be an explicit nil
func (o *LoanDisbursementsIndicators) SetDaysSinceLastOccurrenceNil() {
	o.DaysSinceLastOccurrence.Set(nil)
}

// UnsetDaysSinceLastOccurrence ensures that no value is present for DaysSinceLastOccurrence, not even an explicit nil
func (o *LoanDisbursementsIndicators) UnsetDaysSinceLastOccurrence() {
	o.DaysSinceLastOccurrence.Unset()
}

// GetPercentageOfIncome returns the PercentageOfIncome field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LoanDisbursementsIndicators) GetPercentageOfIncome() float64 {
	if o == nil || o.PercentageOfIncome.Get() == nil {
		var ret float64
		return ret
	}
	return *o.PercentageOfIncome.Get()
}

// GetPercentageOfIncomeOk returns a tuple with the PercentageOfIncome field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LoanDisbursementsIndicators) GetPercentageOfIncomeOk() (*float64, bool) {
	if o == nil  {
		return nil, false
	}
	return o.PercentageOfIncome.Get(), o.PercentageOfIncome.IsSet()
}

// HasPercentageOfIncome returns a boolean if a field has been set.
func (o *LoanDisbursementsIndicators) HasPercentageOfIncome() bool {
	if o != nil && o.PercentageOfIncome.IsSet() {
		return true
	}

	return false
}

// SetPercentageOfIncome gets a reference to the given NullableFloat64 and assigns it to the PercentageOfIncome field.
func (o *LoanDisbursementsIndicators) SetPercentageOfIncome(v float64) {
	o.PercentageOfIncome.Set(&v)
}
// SetPercentageOfIncomeNil sets the value for PercentageOfIncome to be an explicit nil
func (o *LoanDisbursementsIndicators) SetPercentageOfIncomeNil() {
	o.PercentageOfIncome.Set(nil)
}

// UnsetPercentageOfIncome ensures that no value is present for PercentageOfIncome, not even an explicit nil
func (o *LoanDisbursementsIndicators) UnsetPercentageOfIncome() {
	o.PercentageOfIncome.Unset()
}

func (o LoanDisbursementsIndicators) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Amount.IsSet() {
		toSerialize["amount"] = o.Amount.Get()
	}
	if o.IsoCurrencyCode.IsSet() {
		toSerialize["iso_currency_code"] = o.IsoCurrencyCode.Get()
	}
	if o.UnofficialCurrencyCode.IsSet() {
		toSerialize["unofficial_currency_code"] = o.UnofficialCurrencyCode.Get()
	}
	if o.CategoryDetails != nil {
		toSerialize["category_details"] = o.CategoryDetails
	}
	if o.MonthlyAverage.IsSet() {
		toSerialize["monthly_average"] = o.MonthlyAverage.Get()
	}
	if o.TopProviders != nil {
		toSerialize["top_providers"] = o.TopProviders
	}
	if o.TransactionsCount.IsSet() {
		toSerialize["transactions_count"] = o.TransactionsCount.Get()
	}
	if o.MonthlySummaries != nil {
		toSerialize["monthly_summaries"] = o.MonthlySummaries
	}
	if o.DaysSinceLastOccurrence.IsSet() {
		toSerialize["days_since_last_occurrence"] = o.DaysSinceLastOccurrence.Get()
	}
	if o.PercentageOfIncome.IsSet() {
		toSerialize["percentage_of_income"] = o.PercentageOfIncome.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *LoanDisbursementsIndicators) UnmarshalJSON(bytes []byte) (err error) {
	varLoanDisbursementsIndicators := _LoanDisbursementsIndicators{}

	if err = json.Unmarshal(bytes, &varLoanDisbursementsIndicators); err == nil {
		*o = LoanDisbursementsIndicators(varLoanDisbursementsIndicators)
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "amount")
		delete(additionalProperties, "iso_currency_code")
		delete(additionalProperties, "unofficial_currency_code")
		delete(additionalProperties, "category_details")
		delete(additionalProperties, "monthly_average")
		delete(additionalProperties, "top_providers")
		delete(additionalProperties, "transactions_count")
		delete(additionalProperties, "monthly_summaries")
		delete(additionalProperties, "days_since_last_occurrence")
		delete(additionalProperties, "percentage_of_income")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLoanDisbursementsIndicators struct {
	value *LoanDisbursementsIndicators
	isSet bool
}

func (v NullableLoanDisbursementsIndicators) Get() *LoanDisbursementsIndicators {
	return v.value
}

func (v *NullableLoanDisbursementsIndicators) Set(val *LoanDisbursementsIndicators) {
	v.value = val
	v.isSet = true
}

func (v NullableLoanDisbursementsIndicators) IsSet() bool {
	return v.isSet
}

func (v *NullableLoanDisbursementsIndicators) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoanDisbursementsIndicators(val *LoanDisbursementsIndicators) *NullableLoanDisbursementsIndicators {
	return &NullableLoanDisbursementsIndicators{value: val, isSet: true}
}

func (v NullableLoanDisbursementsIndicators) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoanDisbursementsIndicators) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


