/*
 * The Plaid API
 *
 * The Plaid REST API. Please see https://plaid.com/docs/api for more details.
 *
 * API version: 2020-09-14_1.457.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plaid

import (
	"encoding/json"
)

// LinkTokenCreateHostedLink Configuration parameters for Hosted Link
type LinkTokenCreateHostedLink struct {
	DeliveryMethod *HostedLinkDeliveryMethod `json:"delivery_method,omitempty"`
	// URI that Hosted Link will redirect to upon completion of the Link flow. This will only occur in Hosted Link sessions, not in other implementation methods. 
	CompletionRedirectUri *string `json:"completion_redirect_uri,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _LinkTokenCreateHostedLink LinkTokenCreateHostedLink

// NewLinkTokenCreateHostedLink instantiates a new LinkTokenCreateHostedLink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLinkTokenCreateHostedLink() *LinkTokenCreateHostedLink {
	this := LinkTokenCreateHostedLink{}
	return &this
}

// NewLinkTokenCreateHostedLinkWithDefaults instantiates a new LinkTokenCreateHostedLink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLinkTokenCreateHostedLinkWithDefaults() *LinkTokenCreateHostedLink {
	this := LinkTokenCreateHostedLink{}
	return &this
}

// GetDeliveryMethod returns the DeliveryMethod field value if set, zero value otherwise.
func (o *LinkTokenCreateHostedLink) GetDeliveryMethod() HostedLinkDeliveryMethod {
	if o == nil || o.DeliveryMethod == nil {
		var ret HostedLinkDeliveryMethod
		return ret
	}
	return *o.DeliveryMethod
}

// GetDeliveryMethodOk returns a tuple with the DeliveryMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkTokenCreateHostedLink) GetDeliveryMethodOk() (*HostedLinkDeliveryMethod, bool) {
	if o == nil || o.DeliveryMethod == nil {
		return nil, false
	}
	return o.DeliveryMethod, true
}

// HasDeliveryMethod returns a boolean if a field has been set.
func (o *LinkTokenCreateHostedLink) HasDeliveryMethod() bool {
	if o != nil && o.DeliveryMethod != nil {
		return true
	}

	return false
}

// SetDeliveryMethod gets a reference to the given HostedLinkDeliveryMethod and assigns it to the DeliveryMethod field.
func (o *LinkTokenCreateHostedLink) SetDeliveryMethod(v HostedLinkDeliveryMethod) {
	o.DeliveryMethod = &v
}

// GetCompletionRedirectUri returns the CompletionRedirectUri field value if set, zero value otherwise.
func (o *LinkTokenCreateHostedLink) GetCompletionRedirectUri() string {
	if o == nil || o.CompletionRedirectUri == nil {
		var ret string
		return ret
	}
	return *o.CompletionRedirectUri
}

// GetCompletionRedirectUriOk returns a tuple with the CompletionRedirectUri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkTokenCreateHostedLink) GetCompletionRedirectUriOk() (*string, bool) {
	if o == nil || o.CompletionRedirectUri == nil {
		return nil, false
	}
	return o.CompletionRedirectUri, true
}

// HasCompletionRedirectUri returns a boolean if a field has been set.
func (o *LinkTokenCreateHostedLink) HasCompletionRedirectUri() bool {
	if o != nil && o.CompletionRedirectUri != nil {
		return true
	}

	return false
}

// SetCompletionRedirectUri gets a reference to the given string and assigns it to the CompletionRedirectUri field.
func (o *LinkTokenCreateHostedLink) SetCompletionRedirectUri(v string) {
	o.CompletionRedirectUri = &v
}

func (o LinkTokenCreateHostedLink) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DeliveryMethod != nil {
		toSerialize["delivery_method"] = o.DeliveryMethod
	}
	if o.CompletionRedirectUri != nil {
		toSerialize["completion_redirect_uri"] = o.CompletionRedirectUri
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *LinkTokenCreateHostedLink) UnmarshalJSON(bytes []byte) (err error) {
	varLinkTokenCreateHostedLink := _LinkTokenCreateHostedLink{}

	if err = json.Unmarshal(bytes, &varLinkTokenCreateHostedLink); err == nil {
		*o = LinkTokenCreateHostedLink(varLinkTokenCreateHostedLink)
	} else {
		return err
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "delivery_method")
		delete(additionalProperties, "completion_redirect_uri")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLinkTokenCreateHostedLink struct {
	value *LinkTokenCreateHostedLink
	isSet bool
}

func (v NullableLinkTokenCreateHostedLink) Get() *LinkTokenCreateHostedLink {
	return v.value
}

func (v *NullableLinkTokenCreateHostedLink) Set(val *LinkTokenCreateHostedLink) {
	v.value = val
	v.isSet = true
}

func (v NullableLinkTokenCreateHostedLink) IsSet() bool {
	return v.isSet
}

func (v *NullableLinkTokenCreateHostedLink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLinkTokenCreateHostedLink(val *LinkTokenCreateHostedLink) *NullableLinkTokenCreateHostedLink {
	return &NullableLinkTokenCreateHostedLink{value: val, isSet: true}
}

func (v NullableLinkTokenCreateHostedLink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLinkTokenCreateHostedLink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


